import type {
  MarketplaceSeedBrand,
  MarketplaceSeedExternalSource,
  MarketplaceSeedProduct,
} from "./marketplace-types"

export const marketplaceBrands: MarketplaceSeedBrand[] = [
  {
    name: "Northline Studio",
    slug: "northline-studio",
    description: "Structured outerwear and travel-ready tailoring from an independent label.",
    websiteUrl: "https://northline.example",
    logoUrl: "/placeholder-logo.svg?height=80&width=80&text=NS",
  },
  {
    name: "Aster Atelier",
    slug: "aster-atelier",
    description: "Minimal occasionwear and fluid evening silhouettes from a boutique brand.",
    websiteUrl: "https://asteratelier.example",
    logoUrl: "/placeholder-logo.svg?height=80&width=80&text=AA",
  },
  {
    name: "Meridian Essentials",
    slug: "meridian-essentials",
    description: "Elevated basics and soft wardrobe staples built for daily wear.",
    websiteUrl: "https://meridian.example",
    logoUrl: "/placeholder-logo.svg?height=80&width=80&text=ME",
  },
]

export const marketplaceExternalSources: MarketplaceSeedExternalSource[] = [
  {
    name: "Northline Brand Site",
    slug: "northline-brand-site",
    kind: "brand_site",
    baseUrl: "https://northline.example",
    metadata: {
      region: "IN",
      channel: "direct",
    },
  },
  {
    name: "Aster Brand Site",
    slug: "aster-brand-site",
    kind: "brand_site",
    baseUrl: "https://asteratelier.example",
    metadata: {
      region: "IN",
      channel: "direct",
    },
  },
  {
    name: "Meridian Brand Site",
    slug: "meridian-brand-site",
    kind: "brand_site",
    baseUrl: "https://meridian.example",
    metadata: {
      region: "IN",
      channel: "direct",
    },
  },
  {
    name: "Edit Board Affiliate Feed",
    slug: "edit-board-affiliate-feed",
    kind: "affiliate_feed",
    baseUrl: "https://shop.editboard.example",
    metadata: {
      region: "IN",
      channel: "affiliate",
    },
  },
]

export const marketplaceProducts: MarketplaceSeedProduct[] = [
  {
    brandSlug: "northline-studio",
    name: "Structured Bomber Jacket",
    slug: "structured-bomber-jacket",
    description: "A clean bomber with matte hardware, padded structure, and a sharp cropped line.",
    price: 129.0,
    image: "/placeholder.svg?height=600&width=500&text=Structured+Bomber",
    status: "active",
    tags: ["outerwear", "black", "structured", "minimal", "citywear"],
    offers: [
      {
        sourceSlug: "northline-brand-site",
        externalOfferId: "northline-bomber-001",
        merchantName: "Northline Studio",
        offerUrl: "https://northline.example/products/structured-bomber-jacket",
        checkoutMethod: "external",
        price: 129.0,
        compareAtPrice: 149.0,
        currency: "INR",
        availability: "in_stock",
        sku: "NS-BOMBER-001",
        inventoryQuantity: 24,
        image: "/placeholder.svg?height=600&width=500&text=Structured+Bomber",
        isPrimary: true,
      },
      {
        sourceSlug: "edit-board-affiliate-feed",
        externalOfferId: "editboard-bomber-001",
        merchantName: "Edit Board",
        offerUrl: "https://shop.editboard.example/northline/structured-bomber-jacket",
        checkoutMethod: "external",
        price: 124.0,
        currency: "INR",
        availability: "in_stock",
        image: "/placeholder.svg?height=600&width=500&text=Structured+Bomber",
      },
    ],
  },
  {
    brandSlug: "northline-studio",
    name: "Pleated Travel Trouser",
    slug: "pleated-travel-trouser",
    description: "A straight-leg trouser with a relaxed rise, lightweight drape, and all-day structure.",
    price: 84.0,
    image: "/placeholder.svg?height=600&width=500&text=Travel+Trouser",
    status: "active",
    tags: ["trousers", "charcoal", "relaxed", "tailoring", "travel"],
    offers: [
      {
        sourceSlug: "northline-brand-site",
        externalOfferId: "northline-trouser-001",
        merchantName: "Northline Studio",
        offerUrl: "https://northline.example/products/pleated-travel-trouser",
        checkoutMethod: "external",
        price: 84.0,
        currency: "INR",
        availability: "in_stock",
        sku: "NS-TROUSER-001",
        inventoryQuantity: 31,
        image: "/placeholder.svg?height=600&width=500&text=Travel+Trouser",
        isPrimary: true,
      },
    ],
  },
  {
    brandSlug: "aster-atelier",
    name: "Silk Column Dress",
    slug: "silk-column-dress",
    description: "A fluid evening dress with a soft column silhouette and subtle back drape.",
    price: 158.0,
    image: "/placeholder.svg?height=600&width=500&text=Silk+Column+Dress",
    status: "active",
    tags: ["dress", "ivory", "slim", "occasion", "evening"],
    offers: [
      {
        sourceSlug: "aster-brand-site",
        externalOfferId: "aster-dress-001",
        merchantName: "Aster Atelier",
        offerUrl: "https://asteratelier.example/products/silk-column-dress",
        checkoutMethod: "external",
        price: 158.0,
        compareAtPrice: 179.0,
        currency: "INR",
        availability: "in_stock",
        sku: "AA-DRESS-001",
        inventoryQuantity: 12,
        image: "/placeholder.svg?height=600&width=500&text=Silk+Column+Dress",
        isPrimary: true,
      },
      {
        sourceSlug: "edit-board-affiliate-feed",
        externalOfferId: "editboard-dress-001",
        merchantName: "Edit Board",
        offerUrl: "https://shop.editboard.example/aster/silk-column-dress",
        checkoutMethod: "external",
        price: 154.0,
        currency: "INR",
        availability: "preorder",
        image: "/placeholder.svg?height=600&width=500&text=Silk+Column+Dress",
      },
    ],
  },
  {
    brandSlug: "aster-atelier",
    name: "Soft Tailoring Vest",
    slug: "soft-tailoring-vest",
    description: "A longline vest with a clean front, fluid arm opening, and sharp shoulder line.",
    price: 92.0,
    image: "/placeholder.svg?height=600&width=500&text=Soft+Tailoring+Vest",
    status: "active",
    tags: ["vest", "sand", "tailored", "tailoring", "layering"],
    offers: [
      {
        sourceSlug: "aster-brand-site",
        externalOfferId: "aster-vest-001",
        merchantName: "Aster Atelier",
        offerUrl: "https://asteratelier.example/products/soft-tailoring-vest",
        checkoutMethod: "external",
        price: 92.0,
        currency: "INR",
        availability: "in_stock",
        sku: "AA-VEST-001",
        inventoryQuantity: 18,
        image: "/placeholder.svg?height=600&width=500&text=Soft+Tailoring+Vest",
        isPrimary: true,
      },
    ],
  },
  {
    brandSlug: "meridian-essentials",
    name: "Washed Rib Tee",
    slug: "washed-rib-tee",
    description: "A soft rib tee with a close fit, washed handle, and slightly elongated sleeve.",
    price: 34.0,
    image: "/placeholder.svg?height=600&width=500&text=Washed+Rib+Tee",
    status: "active",
    tags: ["tee", "white", "fitted", "essentials", "basics"],
    offers: [
      {
        sourceSlug: "meridian-brand-site",
        externalOfferId: "meridian-tee-001",
        merchantName: "Meridian Essentials",
        offerUrl: "https://meridian.example/products/washed-rib-tee",
        checkoutMethod: "external",
        price: 34.0,
        currency: "INR",
        availability: "in_stock",
        sku: "ME-TEE-001",
        inventoryQuantity: 70,
        image: "/placeholder.svg?height=600&width=500&text=Washed+Rib+Tee",
        isPrimary: true,
      },
    ],
  },
  {
    brandSlug: "meridian-essentials",
    name: "Relaxed Knit Polo",
    slug: "relaxed-knit-polo",
    description: "A breathable knit polo with a soft collar, dropped shoulder, and easy drape.",
    price: 58.0,
    image: "/placeholder.svg?height=600&width=500&text=Relaxed+Knit+Polo",
    status: "active",
    tags: ["knitwear", "olive", "relaxed", "minimal", "weekend"],
    offers: [
      {
        sourceSlug: "meridian-brand-site",
        externalOfferId: "meridian-polo-001",
        merchantName: "Meridian Essentials",
        offerUrl: "https://meridian.example/products/relaxed-knit-polo",
        checkoutMethod: "external",
        price: 58.0,
        compareAtPrice: 64.0,
        currency: "INR",
        availability: "in_stock",
        sku: "ME-POLO-001",
        inventoryQuantity: 29,
        image: "/placeholder.svg?height=600&width=500&text=Relaxed+Knit+Polo",
        isPrimary: true,
      },
    ],
  },
]
